-- =====================================================================
-- V1：创建 users 表
-- =====================================================================
-- 关于 Flyway 的命名规则（很重要，写错就不执行）：
--   V1__create_users_table.sql
--   │  │  └── 描述部分，随便写，用下划线分隔
--   │  └───── 两个下划线！一个下划线 Flyway 认不出来
--   └──────── V + 版本号，执行顺序就按这个数字从小到大
--
-- 已经执行过的脚本**不能再改**。想调整表结构就新加一个 V2__xxx.sql，
-- Flyway 会在每张表里记下"哪些版本已经跑过"（表名 flyway_schema_history），
-- 下次启动只跑新的那些。改了旧脚本 Flyway 会直接报校验失败 —— 这是特性不是 bug，
-- 因为它保证了"所有人的数据库都是同一套演变历史"。
--
-- 为什么不用 Hibernate 的 ddl-auto=update 自动建表？
--   因为那样表结构是"跟着 Java 类变"的，你看不到它到底执行了什么，
--   也没法把某一次改动单独拎出来部署。手写 SQL 才能一眼看清表长什么样。
-- =====================================================================

CREATE TABLE users (
    -- 主键，自增。用标准 SQL 写法（而不是 H2 特有的 IDENTITY 类型），
    -- 这样将来换到 PostgreSQL 也是同一句话。
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- 登录账号。长度 50，不许为空，不许重复。
    username      VARCHAR(50)  NOT NULL,

    -- 密码的哈希值，不是明文。BCrypt 固定 60 字符，留余量给 100。
    password_hash VARCHAR(100) NOT NULL,

    -- 注册时间
    created_at    TIMESTAMP    NOT NULL,

    -- 给唯一约束起个名字（uk = unique key），
    -- 将来报"违反唯一约束"时错误信息里会带上这个名字，比数据库自动起的乱码好查得多。
    CONSTRAINT uk_users_username UNIQUE (username)
);
