package io.github.genjitsutouhijk.demo.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.time.LocalDateTime;

/**
 * 用户表在代码里的样子（JPA 把这种类叫"实体"，entity）
 *
 * 一句话理解实体类：
 *   一个类 = 一张表，一个字段 = 一列，一个对象 = 一行数据。
 *
 * ┌──────────────────────┐         ┌──────────────────────────────────────────┐
 * │ Java 这边            │         │ 数据库这边（users 表）                    │
 * ├──────────────────────┤         ├──────────────────────────────────────────┤
 * │ class User           │  ←→     │ CREATE TABLE users (...)                 │
 * │   Long id            │  ←→     │   id            BIGINT                   │
 * │   String username    │  ←→     │   username      VARCHAR(50)              │
 * │   String passwordHash│  ←→     │   password_hash VARCHAR(100)             │
 * │   LocalDateTime ...  │  ←→     │   created_at    TIMESTAMP                │
 * └──────────────────────┘         └──────────────────────────────────────────┘
 *
 * 注意 ↑ 左边叫 passwordHash（驼峰），右边叫 password_hash（下划线）。
 *   数据库的命名习惯用下划线，Java 的命名习惯用驼峰，这是两个圈子的约定不同。
 *   本项目在每个字段上都写了 @Column(name = "...")，把对应关系写死、写明白，
 *   而不是依赖"自动转换驼峰"的默认规则 —— 那样出事的时候很难查。
 *
 * ⚠️ 表名为什么叫 users 而不是 user？
 *   因为 user 是 SQL 里的保留字（很多数据库里和"当前登录用户"有关），
 *   直接拿去当表名，写 SQL 时就得处处加引号或反引号。加个 s 是最省事的做法。
 *
 * ⚠️ 这个类不设 setter 给 id 和 username：
 *   它们一旦写进数据库就不该被改（id 是主键，username 是登录账号）。
 *   少一个 setter，就少一条"被误改"的路。
 */
@Entity
@Table(name = "users")
public class User {

    /**
     * 主键
     *
     * @Id                            —— 标记这个字段是主键
     * @GeneratedValue(IDENTITY)      —— 主键的值让数据库自己生成（自增），
     *                                   我们 new 对象时不用管它，save 完 Hibernate 会把生成的值回填进来。
     *                                   IDENTITY 对应 H2 的 "GENERATED BY DEFAULT AS IDENTITY"。
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    /** 登录账号。nullable=false 表示不能为空，unique=true 表示全表不允许重复。 */
    @Column(name = "username", nullable = false, length = 50, unique = true)
    private String username;

    /**
     * 密码的哈希值，**不是明文**。
     *
     * 长度为什么给 100？
     *   BCrypt 算出来的结果固定是 60 个字符，留点余量写 100，
     *   万一将来换成更长的算法（比如 Argon2）也不用改表。
     */
    @Column(name = "password_hash", nullable = false, length = 100)
    private String passwordHash;

    /** 注册时间。用 LocalDateTime 对应数据库的 TIMESTAMP。 */
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    /**
     * 空构造器 —— 必须有，哪怕它看起来毫无用处，删掉程序就起不来。
     *
     * 为什么？
     *   Hibernate 从数据库读到一行数据后，造对象的流程是：
     *     ① 先 new 一个"什么都没有"的 User（就是走这个空构造器）；
     *     ② 再用反射把每个字段的值直接塞进去。
     *   它不会去调你写的带参构造器。所以 JPA 规范强制要求实体有无参构造器。
     *
     * 为什么是 protected 而不是 public？
     *   给 Hibernate 用就足够了，同时挡住"业务代码随手 new 一个空 User"。
     */
    protected User() {
    }

    /** 业务代码用这个构造器创建新用户（此时 id 还没有，createdAt 由调用方决定）。 */
    public User(String username, String passwordHash, LocalDateTime createdAt) {
        this.username = username;
        this.passwordHash = passwordHash;
        this.createdAt = createdAt;
    }

    public Long getId() {
        return id;
    }

    public String getUsername() {
        return username;
    }

    public String getPasswordHash() {
        return passwordHash;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * 只有密码是允许被改的（将来做"修改密码"时会用到）。
     * 注意传进来的必须是**已经加密过**的哈希值，不能是明文 ——
     * 这个约定由 UserService 那一层保证，实体本身不负责加密。
     */
    public void changePasswordHash(String newPasswordHash) {
        this.passwordHash = newPasswordHash;
    }
}
